### PR TITLE
Ft send travel request

### PR DESCRIPTION
**Pull request by CYIMANA-Faisal**
# Description

This set up a project from scratch without using npx create-react-app

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How should this be manually tested or reproduced?

- Clone this repo
- Run the command `npm i`
- Run the command `npm start`

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots (if applicable)

### CODE REVIEW

**Review by salviosage — CHANGES_REQUESTED** [review]
Please check failing checks and rebase @CYIMANA-Faisal

**Comment by salviosage** [comment]
Please rebase

**Review by edgar929 — APPROVED** [review]
good job, it is working fine

**Review by Blaiseniyo — APPROVED** [review]

**Review by mfrank37 — APPROVED** [review]

**Review by Noel2002 — COMMENTED** [review]
some routes and functionalities are missing on this routes while they have been merged on develop. Those functionalities include managing direct reports and admin roles' management. that is what i was able to notice

Try to rebase and see if they work.

**Review by Noel2002 — APPROVED** [review]

**Pull request closed without merging**
