### PR TITLE
Ft update profile page

### PR DESCRIPTION
**Pull request by edgar929**
# Description

This set up a project from scratch without using npx create-react-app

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How should this be manually tested or reproduced?

- Clone this repo
- Run the command `npm i`
- Run the command `npm start`

# Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots (if applicable)

### CODE REVIEW

**Comment by Anguandia** [comment]
@edgar929 Please check your PR description, and how should I manually test this feature?

**Review by songa1 — DISMISSED** [review]

**Comment by mfrank37** [comment]
Please fix the Node.js CI / build.

**Review by Blaiseniyo — COMMENTED** [review]
I have seen that now the navbar on the landing page is now working even the logout is now working very well, But if you would look at the way the navbar is looking on the landing page and consider changing it, below is the screen of the way it is now
navbar

if you can change the login and the signup to be aligned on the same horizontal line instead of being on a vertical line, and also display the barefoot nomad on one line instead of breaking it on multiple lines

**Review by Blaiseniyo — COMMENTED** [review]
Another thing on updating the profile, when someone updates the profile and it is still in progress if you can display a loader while his waiting. because maybe the now it faster because we are using local server put when we use the production server it may take time so it would be better if we display it to show the work is still in progress

**Comment by Anguandia** [comment]
@edgar929, please respond to Blaise and Frank's reviews

**Comment by edgar929** [comment]
@Blaiseniyo  i don't know why on your end, the navbar looks that way but on my side it aligned well

**Comment by edgar929** [comment]
> Please fix the Node.js CI / build.

thanks

**Comment by edgar929** [comment]
> Another thing on updating the profile, when someone updates the profile and it is still in progress if you can display a loader while his waiting. because maybe the now it faster because we are using local server put when we use the production server it may take time so it would be better if we display it to show the work is still in progress

i don't know why on your end, the navbar looks that way but on my side it aligned well

**Review by CYIMANA-Faisal — COMMENTED** [review]
The functionality is working well but I failed to run the tests, please describe the way your test can be run locally

**Comment by edgar929** [comment]
> The functionality is working well but I failed to run the tests, please describe the way your test can be run locally

npm run test, i have 2 failing tests from other files not mine. and i was not able to solve them

**Review by Blaiseniyo — APPROVED** [review]

**Review by songa1 — APPROVED** [review]
This feature is working well

**Review by CYIMANA-Faisal — APPROVED** [review]

**Review by Alice-Gatera — APPROVED** [review]

**Pull request merged**
